### ISSUE TITLE
"Remove everyone from role" not working, even for active users

### ISSUE THREAD

**Issue by DoctorDinosaur** [countr/countr#119]
# Bug Report

Created a flow to give the last person to count a role, and the last person to fail a different role.

Tried twice, both times it successfully grants the roles but never removes them. Hence the people with the role just stack up until there's loads of them

## Reproducing
Created the following flows

![image](https://user-images.githubusercontent.com/26852749/121727042-4a6d5c00-cae3-11eb-9c11-d69a391f227d.png)

Then, when two people count, both of them end up with the Maths Genius role.

(It worked sometimes, but hardly ever. I assume this is the caching issue but all users were active, and there were whole minutes between counts sometimes)

## Expected behavior

The Maths Genius role would be removed from everyone, then given to the last person to count.
When the count is failed, the Cant Count role is taken from everyone then given to the person that failed the count.

## Alternative Solution (If it is a caching issue)
Using the same system that stops people from counting twice (i.e. tracking the last person to count), add an action/command to give this person a role.

However this doesn't solve my issue with the failed count role. So "take role from everyone" still needs fixing.

Also, could add an action like "Give unique role", that instead of iterating over all users just tracks who has the role in DB and removes from the last person.

## Screenshots
![image](https://user-images.githubusercontent.com/26852749/121727750-39711a80-cae4-11eb-9268-04dd151e141f.png)

**Comment by promise** [comment]
It's just an issue with caching in general. When the Countr cache fills up, it can't store more members in the memory and basically just gives up. I will see if there's another solution to this in djs^13.

I've heard Discord is working on an endpoint to set a role's members, but this was a while ago so I'm unsure if they just gave up on it or didn't bother adding it at all.

**Comment by promise** [comment]
Should be fixed now. Read here for more information: https://f17f0d62.countr.pages.dev/docs/troubleshooting#role-member-caching

**Comment by DoctorDinosaur** [comment]
Still not working
![image](https://user-images.githubusercontent.com/26852749/185748557-61547da5-570b-40fb-8089-4498660d0f38.png)
I end up with multiple people with the role. Perhaps its moving too quickly, since I'm doing it every number.


It's computationally easier if you could add an action to "Give unique role"
Which caches just the single previous owner, removes it from them, and gives it to the new owner.
Much less memory usage.
